import type { Metadata } from "next";
import { Playwrite_US_Modern } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";

const myfont = Playwrite_US_Modern({
  weight: ['200', '400'],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${myfont.className} antialiased background-img`}
      >
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  );
}
